### ISSUE TITLE
Bot doesn't allow overwrite of Ethaddress with !she addaddress command.

### ISSUE THREAD

**Issue by decryptifyingtheodds** [ShenaniganDApp/ShenaniganDApp.github.io#35]
Ran into a user today that seems to have put the wrong eth address, and would like to update it. 

Issue: User wants to change their eth address with command !she addaddress <ethaddress>. However when you try to update the new address the bot says "@apupnamedrusty, You have already registered your address."

Workaround: Unsure, but most likely admins will have access to update the database with the right ethaddress.

Proposed fix: Update the command to allow for an overwrite of the previous data stored. OR Create a new command that updates the previous data. I kind of like the idea of having !she updateaddress <ethaddress> because the current command will let the user know that an eth address is on file. We could even add another command that spits out the current eth address so the user can see what is currently stored.

**Comment by youngkidwarrior** [comment]
This should go in the bot repository

Closing this, but i'll handle it in bot
